import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Pokemon } from "./components/Pokemon";

interface Vote {
  voteFor: number,
  voteAgainst: number
}

const Home: NextPage = () => {
  const {data: pokePair, refetch} = trpc.useQuery(["pokemon.getPokemonPair"], {
    refetchInterval: false,
    refetchOnReconnect: false,
    refetchOnWindowFocus: false,
  });
  const voteMutation = trpc.useMutation("pokemon.vote");

  const vote = async (input: Vote) => {
    refetch();
    await voteMutation.mutate(input);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="mt-auto text-4xl text-center">Keep One, Leave One: Pokemon Edition</h1>
        <div className="flex items-center justify-center w-full gap-12 pt-12 text-4xl ">
          {pokePair && pokePair.first && pokePair.second ? (
            <>
              <Pokemon pokemon={pokePair.first} vote={() => {vote({voteFor: pokePair.first.code, voteAgainst: pokePair.second.code});}}/>
              <p>VS.</p>
              <Pokemon pokemon={pokePair.second} vote={() => {vote({voteFor: pokePair.second.code, voteAgainst: pokePair.first.code});}}/>
            </>
          ) : (
            "Loading..."
          )}
        </div>
      </main>
    </>
  );
};
export default Home;
